-- The schema migration is enough to start. To populate real businesses,
-- hit POST /api/leads/seed-osm from the deployed app (or click "Pull
-- real businesses" on the dashboard). That endpoint queries OpenStreetMap
-- for welders, fabricators, and gas suppliers across three UK industrial
-- estates (Park Royal, Slough Trading Estate, Trafford Park) and creates
-- real leads from them — real names, real addresses, real coordinates.
